project:
  type: website
  output-dir: docs

website:
  title: "PK blog"
  navbar:
    title: "J. Paul Kelleher"
    left:
      - text: About
        href: https://paulkelleher.net
      - text: Research
        href: https://paulkelleher.net/research/
      - text: Book
        href: https://paulkelleher.net/sccbook/
      - text: Blog
        href: /
    right:
      - icon: search
  sidebar:
    search: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    cap-location: margin
    reference-location: margin
    fontsize: 1.125em
    linestretch: 1.6
    mainfont: "Source Sans Pro, sans-serif"
    monofont: "Source Code Pro, monospace"

bibliography: /Users/jkelleher/Dropbox/Zotero_JSON_Library/MyLibrary.json
csl: mis-quarterly-2.csl

editor: visual
