project:
  type: website
  output-dir: docs

website:
  title: "PK blog"
  navbar:
    left: 
      - url: https://www.paulkelleher.net
        text: Back to main
  sidebar:
    search: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    cap-location: margin
    reference-location: margin
    fontsize: 1.125em
    linestretch: 1.6
    mainfont: "Source Sans Pro, sans-serif"
    monofont: "Source Code Pro, monospace"

bibliography: /Users/jkelleher/Dropbox/Zotero_JSON_Library/MyLibrary.json
csl: mis-quarterly-2.csl

editor: visual
